### ISSUE TITLE
Graceful failure handling when discord API is offline

### ISSUE THREAD

**Issue by Skyedra** [TechGuard/MantisBT-Discord#2]
In the event discord's API is down or unreachable (which seems to be frequent recently), it would be better if:

- Do not show an error to the user.  Currently this plugin generates an error (below) and makes users think their bug/action was not submitted, even though it was.
- Ideally retry the action later on

Perhaps decouple the notification from the actions?  IE have them queue up into the database, and then have a cron script run through and process notifications.

```
APPLICATION ERROR #plugin_Discord_ERROR_CURL

The request to Discord didn't go through. Check your webhook URL. Also make sure there are no unusual characters in your bot name or bot icon settings. Further details may be printed below this box.
Please use the "Back" button in your web browser to return to the previous page. There you can correct whatever problems were identified in this error or select another action. You can also click an option from the menu bar to go directly to a new section.
```

PS - Great plugin btw :)

**Comment by SugarD-x** [comment]
I agree with this. That would be awesome!

**Comment by c-schmitz** [comment]
ALso +1 from me.

**Comment by c-schmitz** [comment]
You can also reproduce it easily by adding a comment in a Mantis isuse, and just attach a file, no text.

**Comment by c-schmitz** [comment]
Just submitted a pull request #3  for this.

**Comment by TechGuard** [comment]
Closing issue, problem should be resolved with @c-schmitz changes.
